### ISSUE TITLE
Can't rotate in clockwise after setting it to true

### ISSUE THREAD

**Issue by iamzaidsoomro** [alabsi91/react-js-progressbar#1]

**Comment by alabsi91** [comment]
`true` is the default value for `clockwise` property, try to change it to `false` if you want to reverse the direction.

**Comment by iamzaidsoomro** [comment]
Yes it is working now @alabsi91 , but this isn't the right way, it is working opposite. When we set it to clockwise true, it goes anticlockwise and vice versa.

**Comment by alabsi91** [comment]
Thank you for the feedback.

Yeah the direction is a bit confusing in this case, the animation direction will depends also on whether the value is increasing or decreasing, you can use the `clockwise` property to reverse this behavior.
